### ISSUE TITLE
nobody2018 - Anyone can take away the reward tokens left by users when updating position via ConvexSpell#openPositionFarm

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-blueberry-judging#21]
nobody2018

high

# Anyone can take away the reward tokens left by users when updating position via ConvexSpell#openPositionFarm

## Summary

When the user updates the position instead of opening a new one, `openPositionFarm` will take out existing collateral and burn. `wConvexPools.burn` will transfer all reward tokens to the ConvexSpell contract. These reward tokens are stuck in the contract. Anyone can take these reward tokens away via `openPositionFarm`/`closePositionFarm`.

## Vulnerability Detail

`wConvexPools.burn` will transfer all reward tokens to the caller.

```solidity
function burn(
        uint256 id,
        uint256 amount
    )
        external
        nonReentrant
        returns (address[] memory rewardTokens, uint256[] memory rewards)
    {
        ...
        // Transfer LP Tokens
        IERC20Upgradeable(lpToken).safeTransfer(msg.sender, amount);

        // Transfer Reward Tokens
        (rewardTokens, rewards) = pendingRewards(id, amount);

        for (uint i = 0; i < rewardTokens.length; i++) {
            IERC20Upgradeable(rewardTokens[i]).safeTransfer(
                msg.sender,
                rewards[i]
            );
        }
    }
```

However, these reward tokens are not handled in `openPositionFarm`, but stuck in ConvexSpell contract. 

```solidity
// 6. Take out existing collateral and burn
        IBank.Position memory pos = bank.getCurrentPositionInfo();
        if (pos.collateralSize > 0) {
            (uint256 pid, ) = wConvexPools.decodeId(pos.collId);
            if (param.farmingPoolId != pid)
                revert Errors.INCORRECT_PID(param.farmingPoolId);
            if (pos.collToken != address(wConvexPools))
                revert Errors.INCORRECT_COLTOKEN(pos.collToken);
            bank.takeCollateral(pos.collateralSize);
->          wConvexPools.burn(pos.collId, pos.collateralSize);
            _doRefundRewards(CVX);
        }
```

Anyone who can open a new position and close it immediately can get these reward tokens stuck in the contract.

```solidity
function closePositionFarm(
        ClosePosParam calldata param,
        IUniswapV2Router02 swapRouter,
        address[][] calldata swapPath
    )
        external
        existingStrategy(param.strategyId)
        existingCollateral(param.strategyId, param.collToken)
    {
        ...
        // 1. Take out collateral - Burn wrapped tokens, receive crv lp tokens and harvest CRV
        bank.takeCollateral(param.amountPosRemove);
->      (address[] memory rewardTokens, ) = wConvexPools.burn(
            pos.collId,
            param.amountPosRemove
        );

        // 2. Swap rewards tokens to debt token
        for (uint256 i = 0; i < rewardTokens.length; i++) {
            //@audit  rewards = rewardTokens[i].balanceOf(address(this)) - fee;
->          uint256 rewards = _doCutRewardsFee(rewardTokens[i]);
            _ensureApprove(rewardTokens[i], address(swapRouter), rewards);
->          swapRouter.swapExactTokensForTokens(
                rewards,
                0,
                swapPath[i],
                address(this),
                type(uint256).max
            );
        }
    ...
    }
```

## Impact

Anyone can take away the reward tokens left by users when updating positions. These users suffer funds loss.

## Code Snippet

https://github.com/sherlock-audit/2023-05-blueberry/blob/main/blueberry-core/contracts/spell/ConvexSpell.sol#L136

https://github.com/sherlock-audit/2023-05-blueberry/blob/main/blueberry-core/contracts/spell/ConvexSpell.sol#L165-L181

https://github.com/sherlock-audit/2023-05-blueberry/blob/main/blueberry-core/contracts/wrapper/WConvexPools.sol#L227-L234

## Tool used

Manual Review

## Recommendation

- Swap reward tokens to debt token.
- Transfer reward tokens to positions's owner.

Duplicate of #29

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is not dup of #29. The issue described in this report occurs in the ConvexSpell contract, while the one described in #29 is in the AuraSpell contract. **They are used by different users, how can they be the same? Although their problems are similar, the positions affected are different**. 
I remembered in the 2023-03-Y2K contest, there were 2 issues that long array caused DOS.  They were considered as different issues because they affected different users.

**Comment by IAm0x52** [comment]
I still think these should be duped together since it is the exact same issue between both contracts. Similar issues that affected multiple contracts were duped together in the last update contract and historically judging has duped issues like these together

https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/128 - Convex and Aura together
https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/124 - Curve and Convex together
https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/47 - Curve and Convex together
https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/60 - Aura Convex and Curve together

**Comment by hrishibhat** [comment]
Escalation rejected

Valid duplicate of #29 
The underlying issue is the same occurring in two different implementations of the same contract.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid duplicate of #29 
> The underlying issue is the same occurring in two different implementations of the same contract. 
> 

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
