### ISSUE TITLE
nobody2018 - Incorrect decimals used as divisor in WCurveGauge#burn

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-blueberry-judging#26]
nobody2018

medium

# Incorrect decimals used as divisor in WCurveGauge#burn

## Summary

When calculating CRV rewards, 1e18 was mistakenly used as the divisor. It should be lptoken's decimals. **WAuraPools/WConvexPools/WIchiFarm all use lptoken's decimals**.

## Vulnerability Detail

```solidity
function burn(
        uint256 id,
        uint256 amount
    ) external nonReentrant returns (uint256 rewards) {
        if (amount == type(uint256).max) {
            amount = balanceOf(msg.sender, id);
        }
        (uint256 gid, uint256 stCrvPerShare) = decodeId(id);
        _burn(msg.sender, id, amount);
        ILiquidityGauge gauge = ILiquidityGauge(gaugeController.gauges(gid));
        require(address(gauge) != address(0), "gauge not registered");
        _mintCrv(gauge, gid);
        gauge.withdraw(amount);
        IERC20Upgradeable(gauge.lp_token()).safeTransfer(msg.sender, amount);
->      uint256 stCrv = (stCrvPerShare * amount) / 1e18;
->      uint256 enCrv = (accCrvPerShares[gid] * amount) / 1e18;
        if (enCrv > stCrv) {
            rewards = enCrv - stCrv;
            CRV.safeTransfer(msg.sender, rewards);
        }
        return rewards;
    }
```

- If the lptoken's decimals is 16, the reward will be reduced by 100 times.
- If the lptoken's decimals is 20, the reward will be increased by 100 times.

## Impact

When the decimals of lptoken are not equal to 18, the rewards given to users are incorrect.

## Code Snippet

https://github.com/sherlock-audit/2023-05-blueberry/blob/main/blueberry-core/contracts/wrapper/WCurveGauge.sol#L156-L157

## Tool used

Manual Review

## Recommendation

```diff
--- a/blueberry-core/contracts/wrapper/WCurveGauge.sol
+++ b/blueberry-core/contracts/wrapper/WCurveGauge.sol
@@ -153,8 +153,9 @@ contract WCurveGauge is
         _mintCrv(gauge, gid);
         gauge.withdraw(amount);
         IERC20Upgradeable(gauge.lp_token()).safeTransfer(msg.sender, amount);
-        uint256 stCrv = (stCrvPerShare * amount) / 1e18;
-        uint256 enCrv = (accCrvPerShares[gid] * amount) / 1e18;
+        uint256 lpDecimals = IERC20Upgradeable(gauge.lp_token()).decimals();
+        uint256 stCrv = (stCrvPerShare * amount) / (10 ** lpDecimals);
+        uint256 enCrv = (accCrvPerShares[gid] * amount) / (10 ** lpDecimals);
         if (enCrv > stCrv) {
             rewards = enCrv - stCrv;
             CRV.safeTransfer(msg.sender, rewards);
```

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is valid M. **There is no guarantee that the lptoken's decimals will always be 18, this is a edge case**.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> This is valid M. **There is no guarantee that the lptoken's decimals will always be 18, this is a edge case**.

You've deleted an escalation for this issue.

**Comment by IAm0x52** [comment]
Still believe this is invalid. All new [CurveLP](https://github.com/curvefi/curve-contract/blob/b0bbf77f8f93c9c5f4e415bce9cd71f0cdee960e/contracts/tokens/CurveTokenV3.vy#L48-L56) is guaranteed to be 18 dp and Curve has never deployed a pool with anything other than 18 dp.

**Comment by securitygrid** [comment]
agreed with 0x52.
