### ISSUE TITLE
Tendency - WIchiFarm.pendingReward will calculate rewards using not up-to-date variables

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-blueberry-judging#6]
Tendency

medium

# #WIchiFarm.pendingReward will calculate rewards using not up-to-date variables

## Summary
[WIchiFarm.pendingReward](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/wrapper/WIchiFarm.sol#L110-L133) function queries [ichiFarm.poolInfo](https://github.com/ichifarm/ichi-farming/blob/206c44b790fbb2a1e3a655685eb3ab8d793c9f00/contracts/ichiFarmV2.sol#L28) struct without first updating the pool reward variables, thereby calculating users pending rewards with not up to date data
## Vulnerability Detail
the [pendingReward ](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/wrapper/WIchiFarm.sol#L110)function is responsible for returning the pending ICHI rewards for a given `ERC1155 token` id and the amount of `LP tokens`
```solidity
    function pendingRewards(
        uint256 tokenId,
        uint amount
    )
        public
        view
        override
        returns (address[] memory tokens, uint256[] memory rewards)
    {
        (uint256 pid, uint256 stIchiPerShare) = decodeId(tokenId);
        uint256 lpDecimals = IERC20MetadataUpgradeable(ichiFarm.lpToken(pid))
            .decimals();
        (uint256 enIchiPerShare, , ) = ichiFarm.poolInfo(pid);   // Here
        uint256 stIchi = (stIchiPerShare * amount).divCeil(10 ** lpDecimals);
        uint256 enIchi = (enIchiPerShare * amount) / (10 ** lpDecimals);
        uint256 ichiRewards = enIchi > stIchi ? enIchi - stIchi : 0;
        // Convert rewards to ICHI(v2) => ICHI v1 decimal: 9, ICHI v2 Decimal: 18
        ichiRewards *= 1e9;
           
             ......

    }
```
notice that the function is getting `enIchiPerShare` from the struct, which is then used to calculate the users reward. Calculating the reward this way, without first [updating the pool](https://github.com/ichifarm/ichi-farming/blob/206c44b790fbb2a1e3a655685eb3ab8d793c9f00/contracts/ichiFarmV2.sol#L176), will result in the user getting the wrong rewards, since outdated variables will be used for calculation

## Impact
Will calculate users rewards wrongly 
## Code Snippet
https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/wrapper/WIchiFarm.sol#L110-L133
## Tool used
Manual Review

## Recommendation

To resolve this, it's important to update the pool first, before getting the users accrued `Ichi per share`.

Consider defining an interface for updating the pool in IIchiFarm.sol, add this:

```solidity
    function updatePool(uint256 pid) external returns (PoolInfo memory pool);
```
then add this to the `pendingRewards `function 

```solidity
    function pendingRewards(
        uint256 tokenId,
        uint amount
    )
        public
        view
        override
        returns (address[] memory tokens, uint256[] memory rewards)
    {
        + .ichiFarm.updatePool(pids);
        (uint256 pid, uint256 stIchiPerShare) = decodeId(tokenId);
        uint256 lpDecimals = IERC20MetadataUpgradeable(ichiFarm.lpToken(pid))
            .decimals();
        (uint256 enIchiPerShare, , ) = ichiFarm.poolInfo(pid);  
        uint256 stIchi = (stIchiPerShare * amount).divCeil(10 ** lpDecimals);
        uint256 enIchi = (enIchiPerShare * amount) / (10 ** lpDecimals);
        uint256 ichiRewards = enIchi > stIchi ? enIchi - stIchi : 0;
        // Convert rewards to ICHI(v2) => ICHI v1 decimal: 9, ICHI v2 Decimal: 18
        ichiRewards *= 1e9;
           
             ......

    }
```

**Comment by Tendency001** [comment]
Escalate for 10 USD

After calling ichi withdraw and harvest it will be better to update the reward variables of the given pool before using the variables, in order to ensure that the variables are up to date

**Comment by sherlock-admin** [comment]
> Escalate for 10 USD
> 
> After calling ichi withdraw and harvest it will be better to update the reward variables of the given pool before using the variables, in order to ensure that the variables are up to date

You've deleted an escalation for this issue.

**Comment by IAm0x52** [comment]
https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/wrapper/WIchiFarm.sol#L173-L187

This is invalid. If we look at where this is called, the contract will always harvest before calling pending rewards. 

https://github.com/ichifarm/ichi-farming/blob/206c44b790fbb2a1e3a655685eb3ab8d793c9f00/contracts/ichiFarmV2.sol#L238-L257

When the rewards are harvested, update pool is called at ichiFarmV2#L242 which means that variables will be up to date before the pending rewards call in WIchiFarm#L187
